# Generated by Django 5.0.2 on 2024-04-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
